### ISSUE TITLE
Source file 'SerializableChangeTrackingCollection.cs' could not be found

### ISSUE THREAD

**Issue by MonDeveloper** [tonysneed/demo-trackable-serialization#1]
Hi Tony, I'm back today from my holidays, sorry for long silence.

I'm gonna test your solution but it doesn't compile, it seems you forgot to commit one new file, here the error I'm receiving:

Error   1   Source file 'SerializableChangeTrackingCollection.cs' could not be found    C:_github\Repos\demo-trackable-serialization\TrackableSerializationDemo\CSC    TrackableSerializationDemo

**Comment by tonysneed** [comment]
Thanks for the catch ... just pushed the file. Should be there now.

**Comment by MonDeveloper** [comment]
I tested it but unfortunately it doesn't fit my need.

You introduced a new class called **SerializableChangeTrackingCollection<*T*>** but you used it only at client side, doing this way you are able to serialize just the hidden properties (the deletedEntities) at the root level.
I try to explain better:
The client retrieves **6** **Order** and it puts these 6 **Order** into a **SerializableChangeTrackingCollection<*Order*>** collection, now the client delete some item of this collection and in this way when this object is serialized it keep the info about the deleted Orders. 

***It Works.***

***But it is not enough*** because I need the same behaviour also for all the recurive collections present into the graph (*for any navigation properties into the POCOs*).

Imagine a different Example (I'll commit this sample into my fork asap):
The client retrieve **1** **Order** together with all its **OrderDetails** (**OrderDetails** is a collection of **OrderDetail**) and it puts this **Order** into a **SerializableChangeTrackingCollection<*Orders*>** collection, now the client is hosting just one **Order** into the **SerializableChangeTrackingCollection<*Orders*>** collection and that **Order** has a collection of **many OrderDetail**; if the client deletes some of those **OrderDetail**, since they are not "**Serializable..**", the information about their deletion will be lost when we serialize and deserialize the client **SerializableChangeTrackingCollection<*Orders*>** collection.
